version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/examples/hello/test"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/examples/hello/stack"
    schedule:
      interval: "weekly"

