name: Terraform Lint

on:
  workflow_call:
    inputs:
      tflint-version:
        description: "TFLint version to use"
        type: string
        default: "v0.50.3"
      lint-path:
        description: "Directory to lint, e.g. 'infra/' or '.'"
        type: string
        default: "."
      tflint-config:
        description: "Path to tflint config file"
        type: string
        default: ".tflint.hcl"

permissions:
  contents: read

jobs:
  lint:
    name: Lint (tflint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: terraform-linters/setup-tflint@eb0f7c1b77f191dee552664e7884849ce3dd5176 # v6
        with:
          tflint_version: ${{ inputs.tflint-version }}
          cache: true
          tflint_config_path: ${{ inputs.tflint-config }}

      - name: Init TFLint
        working-directory: ${{ inputs.lint-path }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: tflint --init

      - name: Run TFLint
        working-directory: ${{ inputs.lint-path }}
        run: tflint --recursive --format compact
